// lib/firebase_options.dart
//
// TODO: Replace this file by running:
//   flutterfire configure --project=YOUR_FIREBASE_PROJECT_ID
//
// This stub exists so the project compiles without Firebase configured.
// It will be auto-generated by FlutterFire CLI.
//
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // Replace this entire file with flutterfire configure output
    throw UnsupportedError(
      'Firebase not configured. Run: flutterfire configure --project=YOUR_PROJECT_ID\n'
      'Then replace lib/firebase_options.dart with the generated file.',
    );
  }
}
